backend/src/app/core/startup.py
This makes it easier to debug problems with pydantic models, typehints etc.
=> log traceback when crashing during startup

backend/src/api/endpoints/analysis.py
There was an old tag declaration that slipped in during a rebase, I think.
=> Fix failing tests due to old tag declaration

frontend/updateAPI.js
On systems using IPv6, connecting to `localhost` errors because the backend listens on `0.0.0.0`, which is an IPv4 address, but `localhost` resolves to the IPv6 address `::1`.
=> Use 0.0.0.0 as backend address when updating openapi spec

.vscode/launch.json, .vscode/settings.json
- launch.json tells VSCode how to run the backend with debugging
- settings.json tells VSCode how to load the .env file for the backend
=> Add backend launch configuration for VSCode

backend/src/app/celery/background_jobs/__init__.py
The module dispatching the celery tasks did not import our celery worker module, which resulted in the celery configuration not being applied in some cases, e.g. when using uvicorn's hot reload functionality.
By referencing the celery tasks directly, we make sure that the celery config used for defining the tasks is also used for dispatching them.
See https://docs.celeryq.dev/en/stable/userguide/application.html#breaking-the-chain for more information.
fixes #219
=> Fix celery configuration not being applied sometimes

backend/.env.example, backend/src/app/core/security.py, backend/src/app/core/startup.py, backend/src/config.py, backend/src/configs/default.yaml, docker/.env.example
- Prevent unaware users from using these public secrets in production
- Prevent false positives from the gitguardian check
=> Remove random JWT Secret examples

.github/workflows/backend_unit_tests.yml, backend/src/app/core/db/sql_service.py, backend/src/app/core/startup.py, backend/src/main.py, backend/src/test/app/core/data/crud/test_project_crud.py, backend/src/test/conftest.py
Running migrations inside our startup process caused them to be run multiple times, once for each worker, in production. While this should be fine, it's better to run migrations only once before even starting the backend.
=> Run migrations before startup script

backend/src/app/core/data/crud/user.py
When the email specified during login didn't exist, the backend returned a 404 code which caused the frontend to say "server not available". It now returns 403 which results in the correct error message on the frontend, and prevents email guessing attacks via the login route as well.
=> Fix login screen error for missing user

.github/workflows/backend_check_schema.yml, .github/workflows/backend_unit_tests.yml, .github/workflows/update-openapi-spec.yml
Before this change, the CI would not run for PRs that had a base different than `mwp_v1`, even after the base was changed back to `mwp_v1`, which resulted in the CI not running in [this PR](https://github.com/uhh-lt/dwts/pull/259) although it should have run.
=> Run CI on all pull requests

backend/src/app/core/startup.py, backend/src/backend_api_entrypoint.sh, backend/src/main.py, backend/src/test/conftest.py
Before this change, starting the backend with a completely empty database would fail, because initializing all the services would require an already migrated database, and we would be running migrations only after initializing the services.
With this, alembic may be invoked multiple times during startup as uvicorn will start workers in batches, but that should not cause any problems.
=> Always run alembic migrations during startup

.pre-commit-config.yaml, .vscode/settings.json, frontend/generateAPI.js, frontend/tsconfig.json, frontend/updateAPI.js, tools/readability/package.json
Our openapi update scripts usually format the `openapi.json` file using prettier. This is now enforced by adding json files to our prettier pre-commit check.
=> Configure prettier pre-commit hook to run on .json files

.editorconfig, .github/workflows/backend_check_schema.yml, .github/workflows/backend_e2e_tests.yml, .github/workflows/backend_unit_tests.yml, .github/workflows/update-openapi-spec.yml, backend/.env.testing.example, backend/.gitignore, backend/src/app/core/db/sql_service.py, backend/src/app/core/startup.py, backend/src/migration/migrate.py, backend/src/test/conftest.py, docker/docker-compose.yml
=> Give tests their own database

backend/src/app/core/data/crud/project.py, backend/src/app/core/data/crud/source_document.py, backend/src/app/core/search/simsearch_service.py
- When a single document is removed, remove it from weaviate
- When a whole project is removed, remove its documents from weaviate
- When all documents in a project are removed, remove them from weaviate. 
> [!NOTE]
> The last endpoint is unused at the moment, maybe we can remove it.
=> Fix docs not being removed from weaviate

frontend/src/auth/AuthProvider.tsx, frontend/src/utils/DateUtils.ts
There was a flaw in the handling of timezones when refreshing access tokens. This fixes it.
=> Fix date handling in refresh tokens

backend/src/app/preprocessing/ray_model_worker/config.yaml, docker/.env.example, docker/docker-compose.yml, frontend/tsconfig.json
When using blip2 on the CPU, it's necessary to set the precision to 32 bits.
Also, fix #316 since it loosely matched the topic of the first commit :D
=> Add blip precision config, ray docker compose profile

backend/src/app/core/data/crud/preprocessing_job.py
Typo. Instead of id uuid is correct
=> Typo in Errorhandling

backend/src/app/core/data/crud/crud_base.py, frontend/src/api/openapi/core/OpenAPI.ts
After some digging i discovered the following problem:
When querying the database for the project the return value seems to be fine and can be interpret by the fastapi jsonable_encoder.
But when the method  _get_action_state_from_orm is called before the jsonable_encode the db_obj seems to change its state.
This is not obvious for me since the method only returns the db_obj as a dict.
If now the jsonable_encoder is called it ends in a RecursionError by the jsonable_encoder.
A quickfix is to convert the db_obj to a dict and then use the jsonable_encoder like in the PR.
There seems to be a known problem in the jsonable_encoder: https://github.com/tiangolo/fastapi/pull/10359
=> Bugfix update_project api route

tools/crawler/README.md, tools/crawler/environment.yml, tools/crawler/pipelines/readability_pipeline.py, tools/crawler/pipelines/write_pipeline.py, tools/crawler/requirements.txt, tools/crawler/settings.py, tools/crawler/spiders/other/website.py, tools/crawler/spiders/spider_base.py, tools/crawler/spiders/utils.py
I updated the crawler:
- new environment / requirements file to easily setup all dependencies
- new website crawler that downloads all in-domain sites
=> Website crawler

backend/src/api/endpoints/authentication.py, backend/src/test/api/endpoints/test_authentication.py, docker/.env.example, docker/docker-compose.yml, docker/nginx.conf, frontend/src/api/openapi/services/AuthenticationService.ts
solves a critical security issue that file assets could be accessed freely by anyone.
now, project-specific files can only be accessed by users belonging to the project
implementation:
- store JWT in secure cookie on login
- cookie data is send automatically by browser for every request (includes images, file downloads)
- added nginx plugin to guard "/content" path -> make request to backend to verify if access is allowed
- added new API endpoint in `authentication.py` for the nginx check: extracts the JWT from cookie and checks with `AuthzUser` 
- remove lighttpd for prod deployments, directly serve files from nginx. (keep lighttpd for frotnend dev)
TODO in follow-up PR: rework temp directory to be under "project/id" so that temp files such as export can be guarded by this as well
=> fix file content auth

backend/src/api/endpoints/annoscaling.py, backend/src/app/core/annoscaling/annoscaling_service.py, backend/src/app/core/data/dto/annoscaling.py, backend/src/app/core/data/orm/source_document_data.py, backend/src/app/core/db/simsearch_service.py, backend/src/app/core/db/vector_index_service.py, backend/src/app/core/db/weaviate_service.py, frontend/src/api/openapi/models/AnnoscalingConfirmSuggest.ts, frontend/src/api/openapi/models/AnnoscalingResult.ts, frontend/src/api/openapi/models/AnnoscalingSuggest.ts, frontend/src/api/openapi/models/SdocSentencePair.ts, frontend/src/api/openapi/services/AnnoscalingService.ts, frontend/src/openapi.json
this PR adds annotation scaling functionality to the backend: given a type of annotation, the system suggests more candidate sentences. this already features advanced candidate filtering by removing any already annotated sentences or the ones that a closest to a negative support set.
so far, the implementation is rather inefficient due to weaviate not supporting batch queries. for larger projects, we need to use another vector index
=> annotation scaling backend implementation

frontend/src/api/AnnoscalingHooks.ts, frontend/src/api/QueryKey.ts, frontend/src/router/routes.tsx, frontend/src/views/analysis/Analysis.tsx, frontend/src/views/analysis/AnnotationScaling/AnnotationScaling.tsx, frontend/src/views/analysis/AnnotationScaling/AnnotationScalingList.tsx
this PR adds a first frontend for the annotation scaling feature: a user can retrieve sentence-level suggestions and confirm/reject (binary classification) the codes
=> annotation scaling frontend v1

backend/src/app/core/data/crud/span_group.py, backend/src/app/core/data/orm/span_group.py, backend/src/app/core/ml/coref_service.py, backend/src/app/core/ml/ml_service.py, backend/src/app/core/ml/quote_service.py, backend/src/app/preprocessing/ray_model_worker/Dockerfile, frontend/src/views/tools/MlAutomation/MlAutomation.tsx
- re-add flash-atto as dependency to ray docker image
- fix UI not sending correct parameters for re-compute jobs
- fix processing documents without any quotes detected
- fix logic to find unprocessed documents per type (quote, coref, ...)
- limit quote detect to documents with lang == 'de'
=> fix broken coref and quote detect
