uhh-lt/dats

- backend/src/app/core/data/crud/annotation_document.py
- backend/src/app/core/data/crud/crud_base.py
- backend/src/app/core/data/crud/source_document_link.py
- backend/src/app/core/data/crud/span_annotation.py
- backend/src/app/core/data/crud/span_text.py
- backend/src/app/docprepro/text/add_custom_html_tags.py
- backend/src/app/docprepro/text/clean_html.py
- backend/src/app/docprepro/text/create_sdoc_links_from_html.py
- backend/src/app/docprepro/text/extract_text_from_html_and_create_source_mapping.py
- backend/src/app/docprepro/text/generate_span_annotations.py
- backend/src/app/docprepro/text/store_metadata_in_db.py
- backend/src/app/docprepro/text/store_span_annotations_in_db.py
- backend/src/app/util/string_builder.py
batch DB inserts, reduce python loops
> backend: greatly improve text-worker import speed

- .github/workflows/crudtests.yml
- backend/src/test/app/core/data/crud/test_code_crud.py
- backend/src/test/app/core/data/crud/test_feedback_crud.py
- backend/src/test/app/core/data/crud/test_project_crud.py
- backend/src/test/app/core/data/crud/test_user_crud.py
- backend/src/test/conftest.py
- docker/compose.py
first backend tests with GH Actions
> Backend tests

- backend/src/app/preprocessing/ray_model_worker/config.yaml
- backend/src/app/preprocessing/ray_model_worker/models/whisper.py
- backend/src/app/preprocessing/ray_model_worker/requirements.txt
Replace whisper-timestamped with faster-whisper
> Faster whisper

- backend/src/app/preprocessing/ray_model_service.py
- backend/src/app/preprocessing/ray_model_worker/apps/vit_gpt2.py
- backend/src/app/preprocessing/ray_model_worker/models/vit_gpt2.py
> Typo vit gpt2

- backend/Dockerfile
- backend/requirements.txt
- backend/src/app/preprocessing/pipeline/__init__.py
- backend/src/app/preprocessing/pipeline/steps/text/create_ppj_from_extracted_images.py
- backend/src/app/preprocessing/pipeline/steps/text/extract_content_in_html_from_word_or_pdf_docs.py
- backend/src/app/preprocessing/preprocessing_service.py
... for PDF and Word Doc import and preprocessing
> Replaced Apache Tika by PyMuPDF and Mammoth

- backend/src/api/endpoints/analysis.py
- backend/src/api/endpoints/annotation_document.py
- backend/src/api/endpoints/span_annotation.py
- backend/src/api/endpoints/span_group.py
- backend/src/app/core/analysis/analysis_service.py
- backend/src/app/core/data/crud/span_annotation.py
- backend/src/app/core/data/dto/analysis.py
- backend/src/app/core/data/dto/span_annotation.py
- backend/src/app/core/data/export/export_service.py
- frontend/src/api/AnalysisHooks.ts
- frontend/src/api/QueryKey.ts
- frontend/src/api/SdocHooks.ts
- frontend/src/api/SpanAnnotationHooks.ts
- frontend/src/api/openapi/index.ts
- frontend/src/api/openapi/models/AnnotatedSegment.ts
- frontend/src/api/openapi/models/AnnotationOccurrence.ts
- frontend/src/api/openapi/models/SpanAnnotationReadResolved.ts
- frontend/src/api/openapi/services/AnalysisService.ts
- frontend/src/features/CrudDialog/SpanAnnotation/SpanAnnotationEditDialog.tsx
- frontend/src/openapi.json
- frontend/src/router/routes.tsx
- frontend/src/store/store.ts
- frontend/src/views/analysis/Analysis.tsx
- frontend/src/views/analysis/AnnotatedSegments/AnnotatedSegments.tsx
- frontend/src/views/analysis/AnnotatedSegments/AnnotatedSegmentsList.tsx
- frontend/src/views/analysis/AnnotatedSegments/SpanAnnotationCard.tsx
- frontend/src/views/analysis/AnnotatedSegments/SpanAnnotationCardList.tsx
- frontend/src/views/analysis/AnnotatedSegments/annotatedSegmentsSlice.ts
- frontend/src/views/annotation/TextAnnotator/TextAnnotator.tsx
- frontend/src/views/whiteboard/nodes/SpanAnnotationNode.tsx
first version of new analysis feature: Coded Segments
> Coded segments

- backend/src/api/endpoints/analysis.py
- backend/src/api/endpoints/analysis_table.py
- backend/src/api/endpoints/annotation_document.py
- backend/src/api/endpoints/authentication.py
- backend/src/api/endpoints/bbox_annotation.py
- backend/src/api/endpoints/code.py
- backend/src/api/endpoints/crawler.py
- backend/src/api/endpoints/document_tag.py
- backend/src/api/endpoints/export.py
- backend/src/api/endpoints/feedback.py
- backend/src/api/endpoints/memo.py
- backend/src/api/endpoints/metadata.py
- backend/src/api/endpoints/prepro.py
- backend/src/api/endpoints/project.py
- backend/src/api/endpoints/search.py
- backend/src/api/endpoints/source_document.py
- backend/src/api/endpoints/span_annotation.py
- backend/src/api/endpoints/span_group.py
- backend/src/api/endpoints/user.py
- backend/src/api/endpoints/whiteboard.py
> Fix type checking errors for route tags

- .github/workflows/backend_e2e_tests.yml
- .github/workflows/backend_unit_tests.yml
- .github/workflows/build-frontend-docker-image.yml
- backend/src/app/core/startup.py
- backend/src/app/preprocessing/ray_model_service.py
- backend/src/test/conftest.py
- backend/src/test_ray.sh
- docker/monkey_patch_docker_compose_for_backend_tests.py
Yesterday, one of my PRs broke the tests and we didn't notice because they've been failing in the CI for a while. This is my attempt to fix them :)
Update:
Got the unit tests to work by disabling the ray container completely. As a side effect, the workflow now completes a lot faster than before :)
I couldn't get the end to end tests to run, but already fixed some errors that occurred.  I think this can be merged as it is, and if we want to tackle the end to end test CI again we can do so in a second PR.
I'd propose to disable the e2e workflow until then, so we don't have failures in our CI all the time:
https://docs.github.com/en/actions/using-workflows/disabling-and-enabling-a-workflow?tool=webui
> Try to fix tests in CI

- docker/.env.example
- docker/docker-compose.yml
> Make backend and frontend containers optional in compose file

- backend/src/api/dependencies.py
- backend/src/api/endpoints/annotation_document.py
- backend/src/api/endpoints/project.py
- backend/src/api/endpoints/search.py
- backend/src/api/endpoints/user.py
- backend/src/app/core/db/sql_service.py
- backend/src/app/core/security.py
- backend/src/app/util/singleton_meta.py
This removes about 35 errors when running `pyright`, chief among those the one when using `SQLService().db_session()` :)
> Fix some typehint errors

- docker/docker-compose.yml
Forgot to add the new env vars to docker-compose.yml :facepalm:
> Add ray env vars to docker-compose.yml

- backend/src/alembic/env.py
Without this change, the backend would not start on my machine. If it was supposed to work without this change, please let me know if I need to change my system configuration :)
> Fix import causing a startup error

- .vscode/settings.json
- backend/src/api/dependencies.py
- backend/src/api/endpoints/project.py
- backend/src/app/core/authorization/authorization_service.py
- backend/src/app/core/data/crud/project.py
- backend/src/app/core/data/dto/action.py
- backend/src/app/core/data/orm/util.py
- backend/src/main.py
- backend/src/test/app/core/data/crud/test_project_crud.py
- backend/src/test/conftest.py
- frontend/src/api/ProjectHooks.ts
This adds authorization checks using a new dependency: `is_authorized`. For now, this is only applied to the project endpoints. If you're happy with how it works, I'd like to create a second PR for extending this mechanism to the rest of the backend.
It's separated so the big repetitive changes are in their own commits to make reviewing easier :)
> Add simple ownership authorization

- .vscode/launch.json
- backend/src/api/endpoints/search.py
- backend/src/app/core/data/dto/search.py
- backend/src/app/core/search/elasticsearch_service.py
- backend/src/app/core/search/search_service.py
- docker/docker-compose.yml
- docker/elasticsearch.yml
- frontend/src/api/SearchHooks.ts
- frontend/src/api/openapi/index.ts
- frontend/src/api/openapi/models/Body_search_search_sdocs.ts
- frontend/src/api/openapi/models/MemoTitleQuery.ts
- frontend/src/api/openapi/services/SearchService.ts
- frontend/src/features/FilterDialog/FilterDialog.tsx
- frontend/src/openapi.json
- frontend/src/views/search/SearchBar/SearchBar.tsx
- frontend/src/views/search/searchSlice.ts
- frontend/src/views/search/useInitSearchFilterSlice.ts
This PR allows us to use the query_string and simple_query string queries of Elasticsearch. With this, the app supports various complex search operations on the content of Source Documents, including boolean operators, negations, nearby search and wildcards.
> ES upgrade

- .editorconfig
- backend/Makefile
- backend/_activate_current_env.sh
- backend/src/app/core/data/repo/repo_service.py
- backend/src/app/core/db/sql_service.py
- backend/src/wipe_database.py
> Add backend makefile with common commands

- .pre-commit-config.yaml
- backend/src/api/endpoints/document_tag.py
- backend/src/app/core/data/crud/document_tag.py
- frontend/src/api/QueryKey.ts
- frontend/src/api/SdocHooks.ts
- frontend/src/api/TagHooks.ts
- frontend/src/api/openapi/services/DocumentTagService.ts
- frontend/src/openapi.json
- frontend/src/views/search/ToolBar/ToolBarElements/TagMenu/TagMenu.tsx
Fix #276 
> [!NOTE]
> the [openapi spec update branch](https://github.com/uhh-lt/dwts/pull/319) should be merged before this.
> Optimize document tagging in search view

- frontend/src/views/search/SearchResults/Table/SearchResultTable.tsx
- frontend/src/views/search/searchSlice.ts
- frontend/tsconfig.json
I tried persisting the column visibility of the table view as well, but always got an error that I could not resolve.
> Persist search state and table row density

- backend/src/api/endpoints/authentication.py
- backend/src/app/core/data/crud/refresh_token.py
- frontend/src/auth/AuthProvider.tsx
Fix #327 
While fixing the above issue, I also found some other issues which I've explained in the respective commit messages.
> Fix token issues

- frontend/src/views/projectsettings/update/ProjectUsers.tsx
> Remove permission checkboxes

- backend/src/api/endpoints/export.py
- frontend/src/api/CrawlerHooks.ts
- frontend/src/api/ExporterHooks.ts
- frontend/src/api/ProjectHooks.ts
- frontend/src/api/ProjectMetadataHooks.ts
- frontend/src/features/CrudDialog/BBoxAnnotation/BBoxAnnotationEditDialog.tsx
- frontend/src/features/Exporter/ExporterTreeSelect.tsx
- frontend/src/features/Snackbar/SnackbarAPI.ts
- frontend/src/features/Snackbar/SnackbarDialog.tsx
- frontend/src/plugins/ReactQueryClient.ts
- frontend/src/views/analysis/Table/TableViewContent.tsx
- frontend/src/views/analysis/TimelineAnalysis/useTimelineAnalysis.ts
- frontend/src/views/annotation/annoSlice.ts
- frontend/src/views/projectsettings/creation/ProjectCreation.tsx
- frontend/src/views/projectsettings/update/CrawlerRunDialog.tsx
- frontend/src/views/projectsettings/update/ProjectDetails.tsx
- frontend/src/views/projectsettings/update/ProjectDocuments.tsx
- frontend/src/views/projectsettings/update/ProjectMetadata.tsx
- frontend/src/views/projectsettings/update/ProjectUpdate.tsx
- frontend/src/views/projectsettings/update/ProjectUsers.tsx
- frontend/src/views/projectsettings/update/metadata/ProjectMetadataAddButton.tsx
- frontend/src/views/search/DocumentViewer/ImageViewer.tsx
- frontend/src/views/search/ToolBar/ToolBarElements/DownloadSdocsButton.tsx
- frontend/src/views/search/searchSlice.ts
- frontend/src/views/settings/settingsSlice.ts
- frontend/src/views/whiteboard/edges/CustomEdge.tsx
- frontend/src/views/whiteboard/nodes/TextNode.tsx
- frontend/src/views/whiteboard/whiteboardUtils.ts
> Better frontend error handling

- backend/Makefile
- backend/src/run_tests.sh
- backend/src/test/app/core/data/crud/test_code_crud.py
- backend/src/test/app/core/data/crud/test_project_crud.py
- backend/src/test/app/core/data/crud/test_refresh_token_crud.py
- backend/src/test/app/core/data/crud/test_user_crud.py
- backend/src/test/conftest.py
- backend/src/test/test_authz_user.py
- frontend/tsconfig.json
> Refactor test fixtures

- backend/src/app/preprocessing/pipeline/steps/audio/convert_to_pcm.py
- backend/src/app/preprocessing/pipeline/steps/video/create_and_store_audio_stream_file.py
- backend/src/app/preprocessing/pipeline/steps/video/generate_webp_thumbnail_for_video.py
Error messages from FFMPEG are now correctly logged.
> Better FFMPEG Logging

- backend/src/api/endpoints/analysis.py
- backend/src/app/core/analysis/analysis_service.py
- backend/src/app/core/data/dto/analysis.py
- frontend/src/api/AnalysisHooks.ts
- frontend/src/api/QueryKey.ts
- frontend/src/api/openapi/index.ts
- frontend/src/api/openapi/models/SampledSdocsResults.ts
- frontend/src/api/openapi/services/AnalysisService.ts
- frontend/src/components/NavBarTop/EditableTypography.tsx
- frontend/src/openapi.json
- frontend/src/router/routes.tsx
- frontend/src/store/store.ts
- frontend/src/views/analysis/Analysis.tsx
- frontend/src/views/analysis/DocumentSampler/BulkDocTagger.tsx
- frontend/src/views/analysis/DocumentSampler/ChartDataPoint.ts
- frontend/src/views/analysis/DocumentSampler/DataCard.tsx
- frontend/src/views/analysis/DocumentSampler/DocumentSampler.tsx
- frontend/src/views/analysis/DocumentSampler/DocumentsBarChart.tsx
- frontend/src/views/analysis/DocumentSampler/DocumentsTable.tsx
- frontend/src/views/analysis/DocumentSampler/SamplingStrategySelector.tsx
- frontend/src/views/analysis/DocumentSampler/SdocTable.tsx
- frontend/src/views/analysis/DocumentSampler/StartRefreshButton.tsx
- frontend/src/views/analysis/DocumentSampler/TagGroupCreator.tsx
- frontend/src/views/analysis/DocumentSampler/documentSamplerSlice.ts
- frontend/src/views/analysis/Table/TableView.tsx
- frontend/src/views/whiteboard/Whiteboard.tsx
I added a new document sampler component which allows to create a representative sample
> Document sampler

- backend/src/api/endpoints/search.py
- backend/src/app/core/data/dto/search.py
- backend/src/app/core/search/elasticsearch_service.py
- backend/src/app/core/search/search_service.py
> Highlight search 189

- backend/.dockerignore
- backend/requirements.txt
- backend/src/app/preprocessing/pipeline/__init__.py
- backend/src/app/preprocessing/pipeline/steps/text/generate_keywords.py
- backend/src/app/preprocessing/pipeline/steps/text/generate_word_frequencies.py
- backend/src/configs/default.yaml
- backend/src/configs/default_localhost_dev.yaml
- docker/.env.example
Using YAKE for KW generation
- https://github.com/LIAAD/yake
- Campos, R., Mangaravite, V., Pasquali, A., Jatowt, A., Jorge, A., Nunes, C. and Jatowt, A. (2020). YAKE! Keyword Extraction from Single Documents using Multiple Local Features. In Information Sciences Journal. Elsevier, Vol 509, pp 257-289
> Better keywords

- frontend/src/components/BBoxAnnotation/BBoxAnnotationTable/bboxFilterSlice.ts
- frontend/src/components/Code/CodeExplorer/CodeExplorer.tsx
- frontend/src/components/FilterDialog/filterSlice.ts
- frontend/src/components/Project/ProjectIdUpdater.tsx
- frontend/src/components/Project/projectSlice.ts
- frontend/src/components/SourceDocument/SdocTable/documentTableFilterSlice.ts
- frontend/src/components/SpanAnnotation/SpanAnnotationTable/satFilterSlice.ts
- frontend/src/components/dialogSlice.ts
- frontend/src/components/tableSlice.ts
- frontend/src/layouts/OneBarLayout.tsx
- frontend/src/layouts/TwoBarLayout.tsx
- frontend/src/layouts/layoutSlice.ts
- frontend/src/store/store.ts
- frontend/src/views/analysis/AnnotatedSegments/annotatedSegmentsSlice.ts
- frontend/src/views/analysis/ConceptsOverTime/cotaSlice.ts
- frontend/src/views/analysis/TimelineAnalysis/timelineAnalysisSlice.ts
- frontend/src/views/analysis/WordFrequency/wordFrequencySlice.ts
- frontend/src/views/annotation/AnnotationMenu/AnnotationMenu.tsx
- frontend/src/views/annotation/AnnotationMenu/useComputeCodesForSelection.ts
- frontend/src/views/annotation/ImageAnnotator/ImageAnnotator.tsx
- frontend/src/views/annotation/TextAnnotator/TextAnnotator.tsx
- frontend/src/views/annotation/annoSlice.ts
- frontend/src/views/logbook/logbookSlice.ts
- frontend/src/views/search/DocumentSearch/SearchDocumentTable.tsx
- frontend/src/views/search/DocumentSearch/searchSlice.ts
- frontend/src/views/search/ImageSearch/imageSearchSlice.ts
- frontend/src/views/search/SentenceSearch/SentenceSimilaritySearch.tsx
- frontend/src/views/search/SentenceSearch/sentenceSearchSlice.ts
- frontend/src/views/search/searchFilterSlice.ts
- frontend/src/views/tools/AutoLogbook/autologbookSlice.ts
Now, most of the global state is reset when switching projects
> rest global state properly

- backend/src/api/endpoints/span_annotation.py
- backend/src/app/core/data/crud/span_annotation.py
- backend/src/app/core/data/dto/span_annotation.py
- frontend/src/api/SpanAnnotationHooks.ts
- frontend/src/api/openapi/models/SpanAnnotationUpdateBulk.ts
- frontend/src/api/openapi/services/SpanAnnotationService.ts
- frontend/src/components/SpanAnnotation/SpanAnnotationEditDialog.tsx
- frontend/src/openapi.json
> Bulk update span annotations

- backend/src/app/core/startup.py
> create demo user

- backend/src/api/endpoints/bbox_annotation.py
- backend/src/api/endpoints/code.py
- backend/src/api/endpoints/document_tag.py
- backend/src/api/endpoints/project.py
- backend/src/api/endpoints/source_document.py
- backend/src/api/endpoints/span_annotation.py
- backend/src/app/core/data/dto/memo.py
- backend/src/test/api/endpoints/test_stories.py
- frontend/src/api/openapi/models/MemoCreate.ts
- frontend/src/components/Memo/MemoDialog/MemoContentBboxAnnotation.tsx
- frontend/src/components/Memo/MemoDialog/MemoContentCode.tsx
- frontend/src/components/Memo/MemoDialog/MemoContentSourceDocument.tsx
- frontend/src/components/Memo/MemoDialog/MemoContentSpanAnnotation.tsx
- frontend/src/components/Memo/MemoDialog/MemoContentTag.tsx
- frontend/src/openapi.json
> Remove project id from memo

- backend/src/app/core/data/crud/document_tag.py
- frontend/src/api/TagHooks.ts
- frontend/src/components/Tag/TagMenu/TagMenu.tsx
- frontend/src/components/tableSlice.ts
- frontend/src/views/analysis/AnnotatedSegments/annotatedSegmentsSlice.ts
- frontend/src/views/analysis/WordFrequency/wordFrequencySlice.ts
- frontend/src/views/logbook/logbookSlice.ts
- frontend/src/views/search/DocumentSearch/searchSlice.ts
In this PR I address feedback of Yannick regarding document tagging performance and row selection issues
> Yannick feedback

- backend/src/app/preprocessing/ray_model_worker/config_cpu.yaml
- backend/src/app/preprocessing/ray_model_worker/config_gpu.yaml
- backend/src/app/preprocessing/ray_model_worker/models/blip2.py
Pinned BLIP2 to a specific revision, since the latest version is incompatible with the projects transformers version. Updating transformers is not immediately possible due to dependency issues.
> Pinned BLIP2 Revision

- backend/src/api/endpoints/authentication.py
- backend/src/app/core/data/llm/ollama_service.py
- backend/src/configs/production.yaml
- backend/src/test/api/endpoints/test_authentication.py
- bin/setup-folders.sh
- docker/.env.example
- docker/.gitignore
- docker/compose.kuma.yml
- frontend/src/api/openapi/services/AuthenticationService.ts
- frontend/src/auth/HandleOIDCLogin.ts
- frontend/src/components/FilterDialog/filterSlice.ts
- frontend/src/components/LLMDialog/steps/EditorStep/ExampleSelection.tsx
- frontend/src/components/LLMDialog/steps/EditorStep/PromptEditorStep.tsx
- frontend/src/views/analysis/ConceptsOverTime/CotaConceptList.tsx
- frontend/src/views/analysis/ConceptsOverTime/CotaConceptListItem.tsx
- frontend/src/views/analysis/TimelineAnalysis/ConceptList.tsx
- frontend/src/views/analysis/TimelineAnalysis/ConceptListItem.tsx
- frontend/src/views/search/DocumentSearch/SearchDocumentTable.tsx
- frontend/src/views/search/Statistics/SearchStatisticsMenu.tsx
- bessere Few-shot example selection
- Model context size erhöht und neue Fehlermeldung
- Concepte können dupliziert werden in Timeline Analysis
- Monitoring mit Uptime Kuma
- Loading indicator bei search view
- Codes werden besser angezeigt bei SearchFilterStatistics
> Climate feedback april

- .vscode/settings.json
- backend/src/api/endpoints/memo.py
- backend/src/app/core/data/llm/memo_generation.py
Memo generation backend feature using ollama
> Memo Generation

- backend/src/common/languages_enum.py
- backend/src/modules/doc_processing/audio/transcription_job.py
- backend/src/modules/doc_processing/doc_processing_dto.py
- backend/src/modules/doc_processing/html/detect_language_job.py
- backend/src/modules/doc_processing/html/spacy_job.py
- backend/src/ray_model_worker/apps/whisper.py
- backend/src/ray_model_worker/config_cpu.yaml
- backend/src/ray_model_worker/config_gpu.yaml
- backend/src/ray_model_worker/dto/whisper.py
- backend/src/ray_model_worker/models/whisper.py
- backend/src/repos/ray_repo.py
- backend/test/api/endpoints/test_stories.py
- backend/test/conftest.py
- frontend/src/api/openapi/models/CrawlerJobInput_Input.ts
- frontend/src/api/openapi/models/CrawlerJobInput_Output.ts
- frontend/src/api/openapi/models/CrawlerJobRead.ts
- frontend/src/api/openapi/models/Language.ts
- frontend/src/api/openapi/models/ProcessingSettings.ts
- frontend/src/api/openapi/services/JobService.ts
- frontend/src/components/DocumentUpload/FileUploadSection.tsx
- frontend/src/components/DocumentUpload/ProcessingSettingsButton.tsx
- frontend/src/components/DocumentUpload/UrlCrawlerSection.tsx
- frontend/src/openapi.json
- tools/importer/dats_api.py
- tools/importer/dats_importer.py
* whisper batching
* multilungual model instead of english-only
* detect language and provide this info
* allow forcing a specific language
* allow processing of video/audio without spoken words by using informative dummy text as placeholder
fixes #569
> transcription improvements
